name:                progen-cli
version:             0.1.0
github:              "githubuser/progen-cli"
license:             BSD3
author:              "dnlmrtnz"
maintainer:          "dandro.dsign@gmail.com"
copyright:           "2019 dnlmrtnz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/progen-cli#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.14
- directory >= 1.3.3.0
- bytestring >= 0.10.0.0
- text >= 1.2.3.0
- containers >= 0.6.0.1
- aeson >= 1.4.2.0
- pathtype >= 0.8.1

library:
  source-dirs: src

executables:
  progen-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - progen-cli
    - optparse-applicative
    - directory
    - bytestring
    - text
    - containers
    - aeson
    - pathtype

tests:
  progen-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - progen-cli
    - hspec
    - optparse-applicative
    - directory
    - bytestring
    - text
    - containers
    - aeson
    - pathtype
